# service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: user-service
